### ISSUE TITLE
RNN mask support

### ISSUE THREAD

**Issue by ianzur** [ROCm/MIOpen#1203]
EDIT: MIOpen does not currently support masking for RNN layers. This a feature request.

I attempted to build my own masked normalization layer, but I cannot run the model on my gpu. 

- tensorflow-nightly (built on machine, a few weeks behind master)
- ROCm stack (4.3.0)  install via `apt`

I do not recieve this error when I run the model soley on my CPU: `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"`

Error + traceback:
```
2021-10-02 14:34:20.959095: W tensorflow/core/framework/op_kernel.cc:1694] OP_REQUIRES failed at cudnn_rnn_ops.cc:1552 : INVALID_ARGUMENT: ROCm MIOpen only supports packed input output.
Traceback (most recent call last):
  File ".../train_autoencoder_with_hpsearch.py", line 451, in <module>
    tuner.search(df, cross_validation)
  File ".../.env/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py", line 176, in search
    self.run_trial(trial, *fit_args, **fit_kwargs)
  File ".../train_autoencoder_with_hpsearch.py", line 200, in run_trial
    model.fit(
  File ".../.env/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 1189, in fit
    tmp_logs = self.train_function(iterator)
  File ".../.env/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File ".../.env/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.CancelledError:  [_Derived_]RecvAsync is cancelled.
         [[{{node broadcast_weights_1/assert_broadcastable/is_valid_shape/else/_1/broadcast_weights_1/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/then/_53/broadcast_weights_1/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/concat/_22}}]] [Op:__inference_train_function_47156]
```

I was wondering if anyone else has run into this issue with masking?

Custom mask normalization layer ~~(I think this is causing the issue, but it could be several other layers that pass the mask)~~:
Error appears when the mask is passed to an RNN layer after the normalization.
```
import numpy as np
import tensorflow as tf


def fake_ragged_data():
    """create fake ragged data, return concatenated data and row splits"""

    examples = []
    examples.append(np.random.rand(4, 3))
    examples.append(np.random.rand(3, 3))
    examples.append(np.random.rand(5, 3))
    examples.append(np.random.rand(2, 3))

    row_splits = [0]
    for i, example in enumerate(examples):
      row_splits.append(example.shape[0] + row_splits[i])

    return np.concatenate(examples).astype(np.float32) * 10, row_splits
  

if __name__ == "__main__":

    ragged_data, row_splits = fake_ragged_data()
    
    # In my real data zeros exist, so I pad and mask with another value
    mask_value = 99

    x = tf.RaggedTensor.tf.RaggedTensor.from_row_splits(ragged_data, row_splits).to_tensor(
        default_value=mask_value, shape=(None, 5, 3)
    )
    # print(x[0])

    # create model (no need to compile, I am not training in this example)
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Masking(mask_value))
    model.add(tf.keras.layers.GRU(6))
    # model.add(tf.keras.layers.LSTM(6)) # LSTM (instead of GRU) also results in the same error.

    model(x)
```

**Comment by junliume** [comment]
Hi @sunway513, could you or someone from TF team take a look at this user issue please?

**Comment by ianzur** [comment]
After further investigation, the issue does not lie in the my masked normalization layer.

Any RNN layer after the masked layer (GRU or LSTM) causes the error. 

[gist minimal reproducible example (sorry it is quite long).](https://gist.github.com/ianzur/6c07e4bbf35fc33b8d49502c97dc1b13)

If this bug should be moved to tensorflow-upstream, please let me know.

error + traceback:
```
W tensorflow/core/framework/op_kernel.cc:1694] OP_REQUIRES failed at cudnn_rnn_ops.cc:1552 : INVALID_ARGUMENT: ROCm MIOpen only supports packed input output.
Traceback (most recent call last):
  File ".../test_rocm_masking.py", line 170, in <module>
    result = model(tensor_x)
  File ".../.env/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File ".../test_rocm_masking.py", line 124, in call
    x = self.layer1(x)
  File ".../.env/lib/python3.9/site-packages/keras/layers/recurrent.py", line 659, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File ".../.env/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File ".../.env/lib/python3.9/site-packages/keras/layers/recurrent_v2.py", line 443, in call
    last_output, outputs, runtime, states = self._defun_gru_call(
  File ".../.env/lib/python3.9/site-packages/keras/layers/recurrent_v2.py", line 515, in _defun_gru_call
    last_output, outputs, new_h, runtime = gpu_gru(**gpu_gru_kwargs)
  File ".../.env/lib/python3.9/site-packages/keras/layers/recurrent_v2.py", line 659, in gpu_gru
    outputs, h, _, _, _ = tf.raw_ops.CudnnRNNV3(
  File ".../.env/lib/python3.9/site-packages/tensorflow/python/util/tf_export.py", line 404, in wrapper
    return f(**kwargs)
  File ".../.env/lib/python3.9/site-packages/tensorflow/python/ops/gen_cudnn_rnn_ops.py", line 1905, in cudnn_rnnv3
    return cudnn_rnnv3_eager_fallback(
  File ".../.env/lib/python3.9/site-packages/tensorflow/python/ops/gen_cudnn_rnn_ops.py", line 2002, in cudnn_rnnv3_eager_fallback
    _result = _execute.execute(b"CudnnRNNV3", 5, inputs=_inputs_flat,
  File ".../.env/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: ROCm MIOpen only supports packed input output. [Op:CudnnRNNV3]
```

**Comment by sunway513** [comment]
Yes, can you help move this ticket to the following forum:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues

cc @deven-amd  @reza-amd for awareness.

**Comment by ianzur** [comment]
Issue moved to [tf-upstream #1460](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1460).

Closing.

**Comment by ianzur** [comment]
This is not a bug, but a feature that does not exist according to tensorflow testing.

This test is marked accordingly:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/7e8f960bb398526aea7e045884101029fd21bddd/tensorflow/python/keras/layers/gru_v2_test.py#L149

Reopening, please mark as feature request.

**Comment by shurale-nkn** [comment]
> This is not a bug, but a feature that does not exist according to tensorflow testing.
> 
> This test is marked accordingly: https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/7e8f960bb398526aea7e045884101029fd21bddd/tensorflow/python/keras/layers/gru_v2_test.py#L149
> 
> Reopening, please mark as feature request.


Hi. Just like Nvidia, we are not going to support the mask (in its pure form) in RNN layers, instead, we support padded data layout for input and output descriptors (using miopenSeqTensorDescriptor_t). The actual length of each sequence must be specified in these descriptors.
As I can see from the link, this is exactly what TensorFlow needed. 
![image](https://github.com/ROCm/MIOpen/assets/37591772/04aee864-3542-4430-8cd5-90bbbfa748df)
